<Project>
  <PropertyGroup>
    <TargetFrameworks>net8.0;net472</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Version>0.1.4</Version>
    <Authors>othercat</Authors>
    <PackageLicenseExpression>GPL-2.0-only</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/othercat/PalSaveEditor</RepositoryUrl>
  </PropertyGroup>
</Project>
