<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>PalSaveEditor</AssemblyName>
    <RootNamespace>PalSaveEditor.WinForms</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PalSaveEditor.Core/PalSaveEditor.Core.csproj" />
  </ItemGroup>
</Project>
