<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net472</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget Condition="'$(TargetFramework)' == 'net472'">x86</PlatformTarget>
    <AssemblyName>PalSaveEditor</AssemblyName>
    <RootNamespace>PalSaveEditor.WinForms</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PalSaveEditor.Core/PalSaveEditor.Core.csproj" />
  </ItemGroup>
</Project>
