<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PalSaveChecker.Core</AssemblyName>
    <RootNamespace>PalSaveChecker.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PalSaveEditor.Core/PalSaveEditor.Core.csproj" />
  </ItemGroup>
</Project>
