<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net472</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget Condition="'$(TargetFramework)' == 'net472'">x86</PlatformTarget>
    <AssemblyName>仙剑98存档检查工具</AssemblyName>
    <RootNamespace>PalSaveChecker.WinForms</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PalSaveChecker.Core/PalSaveChecker.Core.csproj" />
  </ItemGroup>
</Project>
